services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    command:
      - --qdrant_host=http://qdrant:6333
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      - qdrant

  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
    volumes:
      - ingestion_qdrant-storage:/qdrant/storage

volumes:
  ingestion_qdrant-storage:
    external: true
