services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      LANGFUSE_HOST: https://us.cloud.langfuse.com
    # Contains LANGFUSE_SECRET_KEY and LANGFUSE_PUBLIC_KEY
    env_file:
      - .env
